Python 3.x support
privacyidea/privacyidea-ldap-proxy pull request #54
Opened 2020-12-25 14:15 UTC by lheckemann

2021-05-28 16:37 UTC, globin commented
@fredreichbier @cornelinux In my eyes this should be ready.

All the tests run successfully and it has been tested actively, too.

2021-05-28 19:23 UTC, cornelinux commented
@plettich should we simply drop python2 support and move to 3?

2021-08-24 15:13 UTC, cornelinux requested changes

2021-08-24 15:13 UTC, cornelinux commented on pi_ldapproxy/proxy.py
> +from six import ensure_str
This does not work out - probably with the six-version we are using in requirements.txt?
We should then also update six to 1.16  in the requirements.txt

~~~
builtins.ImportError: cannot import name 'ensure_str' from 'six' (.../ldapproxy/lib/python3.8/site-packages/six.py)
~~~

2021-08-24 17:08 UTC, cornelinux commented on pi_ldapproxy/proxy.py
> +from six import ensure_str
OK, I will update the reqs on my own.

2021-08-24 17:09 UTC, merged